Feature/rails server
criticalmassbr/dialog-devcontainers pull request #1
Opened 2022-03-25 18:32 UTC by luk3skyw4lker

Add admin dockerization config

2022-03-28 14:20 UTC, LucasRMP requested changes

2022-03-28 19:25 UTC, jppachecop commented on .docker/pwa/entrypoint.sh
> +CLIENT=meta yarn dev
O cliente não deveria ser recebido como parâmetro?

2022-03-28 19:36 UTC, jppachecop approved these changes

2022-03-29 12:53 UTC, LucasRMP approved these changes

2022-03-29 13:16 UTC, merged